"""Init database

Revision ID: 50940bcb3738
Revises: 
Create Date: 2022-06-25 23:51:37.142286

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import datetime

# revision identifiers, used by Alembic.
revision = '50940bcb3738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=True, comment='Сайт конкурса'),
    sa.Column('published_date', sa.DateTime(timezone=datetime.timezone.utc), nullable=True, comment='Дата публикации'),
    sa.Column('deadline_date', sa.DateTime(), nullable=True, comment='Дата дедлайна'),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_id'), 'contest', ['id'], unique=False)
    op.create_index(op.f('ix_contest_source_id'), 'contest', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_source_id'), table_name='contest')
    op.drop_index(op.f('ix_contest_id'), table_name='contest')
    op.drop_table('contest')
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_table('source')
    # ### end Alembic commands ###
