"""empty message

Revision ID: df90c2902d23
Revises: 1c2a24af09b3
Create Date: 2022-07-27 07:57:38.105140

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import datetime


# revision identifiers, used by Alembic.
revision = 'df90c2902d23'
down_revision = '1c2a24af09b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('education_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'education_type')
    # ### end Alembic commands ###
